server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mgjun/spring-cloud-config-test.git
          searchPaths: config
          username: mgjun
          password: '{cipher}89aecf4409410f8399f0ca472ae63924e114e1cc5e1312b65978fa232e070f50'
        overrides:
          foo: foo test
      label: master
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456